import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import ImgCarousel from '../components/carousel/ImgCarousel';
import Destinations from '../components/destinations/Destinations'
import Footer from '../components/footer/Footer';
import Hero from '../components/hero/Hero'
import Navbar from '../components/navbar/Navbar'
import Search from '../components/search/Search';
import Selects from '../components/selects/Selects';
export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div>
        <Navbar />
        <Hero />
        <Destinations />
        <Search />
        <Selects />
        <ImgCarousel />
        <Footer />
      </div>

    </div>
  )
}
